version: '3.8'
services:
  srv1:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../srv1:/srv1
    command: sleep infinity
  
  db1:
    image: mongo:latest
    restart: unless-stopped
    # ports:
    #   - '27017:27017'
    volumes:
      - ../db1:/data/db

  db2:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - '5432:5432'
    volumes: 
      - ../db2:/var/lib/postgresql/data
 

# volumes:
#   mongodb-data: